### ISSUE TITLE
"ValueError: Unknown layer: Functional" when running vowel discrimination experiments

### ISSUE THREAD

**Issue by orasanen** [SPEECHCOG/metaeval_experiments#1]
(metaeval_env) [rasaneno@nag07 vowel_discrimination]$ python pc_predictions_calculation/calculate_pc_predictions.py --input_features_path /scratch/gdmacr/interspeech_paper_2022/metaeval_tests/input_features/ivc_input_features.h5 --output_path /scratch/rasaneno/metaeval/ --model_path /scratch/rasaneno/metaeval/trained_models/apc/mfcc/apc_english_2022_09_28_15_02/apc_english_2022_09_28_15_02_epoch-9.h5 --pc_model apc
2022-09-29 12:27:05.939151: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-09-29 12:27:05.959891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:82:00.0 name: Tesla P100-PCIE-12GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 511.41GiB/s
2022-09-29 12:27:05.980141: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2022-09-29 12:27:06.195130: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2022-09-29 12:27:06.299281: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2022-09-29 12:27:06.471101: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2022-09-29 12:27:06.603919: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2022-09-29 12:27:06.663602: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2022-09-29 12:27:06.818211: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2022-09-29 12:27:06.819479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "pc_predictions_calculation/calculate_pc_predictions.py", line 67, in <module>
    create_pc_predictions_file(args.model_path, input_features, args.output_path, args.pc_model)
  File "pc_predictions_calculation/calculate_pc_predictions.py", line 36, in create_pc_predictions_file
    model = load_model(model_path, compile=False)
  File "/home/rasaneno/.conda/envs/metaeval_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/rasaneno/.conda/envs/metaeval_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/rasaneno/.conda/envs/metaeval_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/rasaneno/.conda/envs/metaeval_env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/home/rasaneno/.conda/envs/metaeval_env/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/rasaneno/.conda/envs/metaeval_env/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 250, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional

**Comment by andrea08** [comment]
This error happens when there is a mismatch between tensorflow version used for training and tf version used for loading the model (to run the experiments)

Conda environment for running the experiments is 2.1 upgrade if you have used a higher tf version for training the models.
